addpath baselines;
addpath misc_lib;
addpath Kronecker_Projection\code\Kronecker;
addpath Kronecker_Projection\code\Kronecker\tptool;
run vlfeat/toolbox/vl_setup
run matconvnet/matlab/vl_setupnn
addpath vlfeat/toolbox
addpath vlfeat/toolbox/misc
addpath matconvnet/examples/
addpath matlab-helpers
addpath vlfeat/toolbox/mex
addpath vlfeat/toolbox/mex/mexw64
